defaults: &defaults
  key: ebao
  secret: Oush5toh1F
  authorize_url: http://service.laobai.com/auth/oauth/authorize
  token_url: http://service.laobai.com/auth/oauth/token

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults